import assert from 'node:assert/strict';
import test from 'node:test';
import {createAlignment,alignmentReducer,alignmentReady,restoreAlignment,project,REFERENCE,JUPITER} from '../lib/alignment.ts';
const act=(s,a)=>alignmentReducer(s,typeof a==='string'?{type:a}:a);
function reference(){let s=act(createAlignment(),'inspect');s=act(s,'fine');for(let i=0;i<6;i++)s=act(s,{type:'move',axis:'x',direction:-1});for(let i=0;i<4;i++)s=act(s,{type:'move',axis:'y',direction:1});return act(s,'reference-check');}
function aligned(){let s=reference();for(let i=0;i<6;i++)s=act(s,{type:'adjust',axis:'x',direction:-1});for(let i=0;i<4;i++)s=act(s,{type:'adjust',axis:'y',direction:1});return act(s,'align-check');}
function found(){let s=act(act(aligned(),'target'),'fine');for(let i=0;i<12;i++)s=act(s,{type:'move',axis:'x',direction:1});for(let i=0;i<6;i++)s=act(s,{type:'move',axis:'y',direction:1});return s;}
test('inspection and completed assembly precede motion',()=>{assert.deepEqual(act(createAlignment(),{type:'move',axis:'x',direction:1}).pointing,createAlignment().pointing);assert(!alignmentReducer(createAlignment(),{type:'inspect'},false).inspected);});
test('off-center reference cannot authorize calibration',()=>{assert.equal(act(act(createAlignment(),'inspect'),'reference-check').phase,'reference');assert.equal(reference().phase,'align');});
test('telescope motion changes both optical fields',()=>{const s=reference(),n=act(s,{type:'move',axis:'y',direction:1});for(const view of ['main','finder'])assert.notEqual(project(s,REFERENCE,view).y,project(n,REFERENCE,view).y);assert.deepEqual(n.offset,s.offset);});
test('finder adjustment changes only finder field with stationary crosshair',()=>{const s=reference(),n=act(s,{type:'adjust',axis:'x',direction:-1});assert.deepEqual(project(s,REFERENCE,'main'),project(n,REFERENCE,'main'));assert.notEqual(project(s,REFERENCE,'finder').x,project(n,REFERENCE,'finder').x);});
test('moving tube during alignment requires new reference check',()=>{const s=act(reference(),{type:'move',axis:'x',direction:1});assert(!s.referenceChecked);assert.equal(s.phase,'reference');assert.deepEqual(act(s,{type:'adjust',axis:'x',direction:1}).offset,s.offset);});
test('wrong star in finder center earns no alignment credit',()=>{const s={...reference(),offset:{x:.24,y:.18}};assert(!act(s,'align-check').aligned);});
test('correct geometry alone does not pass without explicit checks',()=>{const s=found();assert(!alignmentReady(s));assert(alignmentReady(act(s,'target-check')));});
test('choosing target does not auto-point telescope',()=>{const s=aligned();assert(s.aligned);const n=act(s,'target');assert.deepEqual(n.pointing,s.pointing);assert(!n.checked);assert(!alignmentReady(n));});
test('finder-only visibility does not count as acquired main target',()=>{const s={...act(aligned(),'target'),pointing:{x:1,y:1}};assert(project(s,JUPITER,'finder').visible);assert(!project(s,JUPITER,'main').visible);assert(!act(s,'target-check').checked);});
test('finder adjustment during target search is rejected',()=>{const s=found(),n=act(s,{type:'adjust',axis:'y',direction:1});assert.deepEqual(n.offset,s.offset);assert(n.events.at(-1).blocked);});
test('movement invalidates target verification but preserves calibrated finder',()=>{const n=act(act(found(),'target-check'),{type:'move',axis:'x',direction:1});assert(!n.checked);assert(n.aligned);});
test('focus locks prior direction and preserves read-only progress',()=>{const s=act(found(),'target-check');for(const type of ['move','adjust','realign','inspect']){const n=alignmentReducer(s,{type,axis:'x',direction:1},true,true);assert.deepEqual(n.pointing,s.pointing);assert(alignmentReady(n));assert(n.events.at(-1).blocked);}});
test('safe partial and complete progress restore; old or malformed completion does not',()=>{assert.equal(restoreAlignment(reference(),true).phase,'align');assert(alignmentReady(restoreAlignment(act(found(),'target-check'),true)));for(const raw of [null,{version:0,checked:true},{...found(),pointing:{x:NaN,y:0}},{...found(),offset:{x:Infinity,y:0}}])assert(!alignmentReady(restoreAlignment(raw,true)));assert(!alignmentReady(restoreAlignment(act(found(),'target-check'),false)));});
test('restore rechecks geometry and cannot credit false target or alignment',()=>{const s=act(found(),'target-check');assert(!alignmentReady(restoreAlignment({...s,pointing:{x:0,y:0}},true)));assert(!alignmentReady(restoreAlignment({...s,offset:{x:1,y:1}},true)));});
test('events bounded and clutches remain locked',()=>{let s=reference();for(let i=0;i<180;i++)s=act(s,'release');assert.equal(s.events.length,160);assert(s.events.every(e=>e.blocked));});
test('main and finder use different field sizes and optical orientation',()=>{const s={...createAlignment(),pointing:{x:0,y:0},offset:{x:0,y:0}};const m=project(s,{x:.1,y:.1},'main'),f=project(s,{x:.1,y:.1},'finder');assert(m.x<0&&m.y<0&&f.x<0&&f.y>0);assert(Math.abs(m.x)>Math.abs(f.x));});
